Don't fail exceptionally if DI server returns error codes
secure-device-onboard/pri-fidoiot pull request #324
Opened 2021-08-02 20:44 UTC by grbean

Signed-off-by: Greg Bean <greg.bean@intel.com>

2021-08-02 22:39 UTC, johneasterday approved these changes

2021-08-02 22:39 UTC, johneasterday approved these changes

2021-08-03 13:30 UTC, KiranSukhavasi requested changes
Please delete this PR. @trbehera @grbean .
This is taken care by @DukeDavis12 in other PR #327  as i see few more exceptions and benny is fixing on top of this.

2021-08-04 07:05 UTC, trbehera commented
Dropped as the PR is extended in #327 .

2021-08-04 07:05 UTC, closed without merging