Hardening code by adding additonal exception handling structures
secure-device-onboard/pri-fidoiot pull request #364
Opened 2021-10-04 04:05 UTC by DukeDavis12

Hardening code by adding additional exception handling structures.
   Policy used: caller function handles all the exceptions thrown by
   the functions in their execution stack.

Signed-off-by: Davis Benny <davis.benny@intel.com>

2021-10-04 07:20 UTC, DukeDavis12 commented on component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java
> +
Remove whitespace

2021-10-04 07:21 UTC, DukeDavis12 commented on component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioFileDownloadServlet.java
> +import java.nio.channels.ScatteringByteChannel;
Remove this import

2021-10-04 07:22 UTC, DukeDavis12 commented on component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioFileUploadServlet.java
> +
remove whitespace

2021-10-04 07:23 UTC, DukeDavis12 commented on component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
> +          "fidoalliance.fdo.device.service.info.mtu";
remove whitespace

2021-10-04 07:25 UTC, DukeDavis12 commented on component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
> +          "fidoalliance.fdo.device.service.info.mtu";
++ Entire file

2021-10-04 07:26 UTC, DukeDavis12 commented on component-samples/manufacturer/src/main/java/org/fidoalliance/fdo/sample/ManufacturerApp.java
> +        logger.error("Error while loading keystore file");
Change error log.

2021-10-04 07:30 UTC, DukeDavis12 commented on http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/DiApiServlet.java
> +        logger.warn("Request failed because of device with given serial was not found.");
Change log statement -- Invalid serial number.

2021-11-08 10:15 UTC, prateekcr requested changes

2021-11-11 17:02 UTC, DukeDavis12 commented on util/http-dispatchers/http-server-dispatcher/src/main/java/org/fidoalliance/fdo/sample/ProtocolHandler.java
> +      if (request.getContentType() == null
Removed.

2021-11-11 17:29 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/cbor/Encoder.java
> +    try {
Removed.

2021-11-11 17:38 UTC, DukeDavis12 commented on http-api-samples/http-api-owner-sample/src/main/java/org/fidoalliance/fdo/api/OwnerCustomerServlet.java
> +    try {
Removed.

2021-11-11 17:50 UTC, DukeDavis12 commented on component-samples/rv/src/main/java/org/fidoalliance/fdo/sample/RvServerApp.java
> +        Path keyStoreFile =
I think it's better to cover the entire section in try-catch as any raised exception, prevents any half-baked httpsConnector object to be created and added to the service.

2021-11-11 17:52 UTC, DukeDavis12 commented on component-samples/rv/src/main/java/org/fidoalliance/fdo/sample/RvContextListener.java
> +    try {
Removed,

2021-11-11 17:53 UTC, DukeDavis12 commented on component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerServerApp.java
> +        Path keyStoreFile =
I think it's better to cover the entire section in try-catch as raised exception, prevents any half-baked httpsConnector object to be created and added to the service.

2021-11-11 17:55 UTC, DukeDavis12 commented on component-samples/manufacturer/src/main/java/org/fidoalliance/fdo/sample/ManufacturerContextListener.java
> +      DiDbStorage db = new DiDbStorage(cs, ds, keyResolver, ods);
Removed.

2021-11-11 17:56 UTC, DukeDavis12 commented on component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioServerApp.java
> +        Path keyStoreFile =
I think it's better to cover the entire section in try-catch as raised exception, prevents any half-baked httpsConnector object to be created and added to the service.

2021-11-11 17:58 UTC, DukeDavis12 commented on component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/DeviceSysModule.java
> +    try {
Done.

2021-11-11 18:01 UTC, DukeDavis12 commented on component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
> +    try {
Let's revisit this again.

2021-11-16 06:09 UTC, DukeDavis12 commented on protocol-samples/http-client-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ClientApp.java
> +    try {
Done.

2021-11-16 06:10 UTC, DukeDavis12 commented on protocol-samples/http-client-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To1ClientApp.java
> +      final MessageDispatcher dispatcher = getDispatcher();
Done.

2021-11-16 06:10 UTC, DukeDavis12 commented on component-samples/rv/src/main/java/org/fidoalliance/fdo/sample/RvServerApp.java
> +        Path keyStoreFile =
Updated.

2021-11-16 06:10 UTC, DukeDavis12 commented on protocol-samples/http-client-to0-sample/src/main/java/org/fidoalliance/fdo/sample/To0ClientApp.java
> +      // Protocol to0_to1_server (rv) only support http so we
Done.

2021-11-16 06:10 UTC, DukeDavis12 commented on component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerServerApp.java
> +        Path keyStoreFile =
Updated.

2021-11-30 04:20 UTC, prateekcr approved these changes

2022-02-01 09:36 UTC, closed without merging