Interop fixes for spec 1.0
secure-device-onboard/pri-fidoiot pull request #381
Opened 2021-11-12 22:33 UTC by rftemple

Signed-off-by: Templeton, Randall <randall.f.templeton@intel.com>

2021-11-15 05:35 UTC, johneasterday approved these changes

2021-11-15 15:45 UTC, johneasterday requested changes
Hold off on merging until client devices can be updated.

2021-11-19 04:20 UTC, DukeDavis12 commented on protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ServerApp.java
> +    ctx.addParameter("webAllowOthers", "true");
Shouldn't it be false?

2022-02-08 15:38 UTC, closed without merging

2022-02-08 15:38 UTC, rftemple commented
All inertop fixed have been implemented in 1.1-dev