Adding logs to Device Component
secure-device-onboard/pri-fidoiot pull request #562
Opened 2022-12-06 06:44 UTC by tPeeush

Adding logs to Device Component.

Signed-off-by: tPeeush <peeush.thakur@intel.com>

2023-01-02 06:55 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceApp.java
> +        logger.info("Generating Device Credential file ");
Please remove whitespace.

2023-01-02 06:56 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceApp.java
> +      logger.error("Operation Creation/Certificate Encoding Execution Failed : " + e.getMessage());
Certificate Creation ?

2023-01-02 06:57 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceValidityDays.java
> +    logger.info("Validity days for device cert request");
Change it to Logger.debug() ; Add validity period also in logs.

2023-01-02 06:57 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceValidityDays.java
> +
Remove whitespace.

2023-01-02 06:59 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java
> +      logger.error("IO Operation Failed");
Exec_CB IO Operation failed + e.getMessage()

2023-01-02 07:03 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/StandardDeviceModule.java
> +      logger.warn("Size of queue = 0 ");
logger.info("Completed DeviceServiceInfo messages");

2023-01-02 07:04 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/StandardMaxServiceInfoSupplier.java
> +    logger.info("SviMtu " + config.getSviMtu());
SVI MTU value:

2023-01-02 07:05 UTC, DukeDavis12 commented on component-samples/device/src/main/java/org/fidoalliance/fdo/sample/UnsupportedCredReuseFunction.java
> +      logger.warn("Don't reuse credentials ");
Device doesn't support credential resuse

2023-01-02 07:06 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/AioRvInfo.java
> +        logger.info("Insert data into RV_DATA");
Inserting

2023-01-02 07:07 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/AllowList.java
> +    logger.debug("committing transaction");
Committing to AllowList Table.

2023-01-02 07:09 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/AllowList.java
> +      logger.warn("Deleting transaction");
Deleted from AllowList table.

2023-01-02 07:09 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/DeviceStateApi.java
> +
Remove whitespace.

2023-01-02 07:11 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/MfgVoucher.java
> +    logger.info("Manufacturing Voucher doGet Path : " + path);
Manufacturing Voucher SerialNo: " + path

2023-01-02 07:13 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/OnDie.java
> +    logger.info("OnDie doPost body : " + body);
Received OnDie POST request;  Add similar one in doGet() also.

2023-01-02 07:14 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/OwnerVoucher.java
> +      logger.error("Not Found Exception for path : " + path);
Voucher not found for GUID: " + path

2023-01-02 07:15 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/ResellApi.java
> +        logger.warn("Not found exception for path " + path);
Voucher not found for GUID: " + path

2023-01-02 07:16 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/RvInfo.java
> +    logger.info("Rv info doGet body : " + body);
RVINFO

2023-01-02 07:17 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/RvInfo.java
> +    logger.info("Rv info doPost body : " + body);
RVInfo

2023-01-02 07:17 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/SviPackage.java
> +      logger.info("SVI package result : " + result);
.debug()

2023-01-02 07:19 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/SystemResourceApi.java
> +    logger.info("filename - " + fileName);
Uploaded File: + fileName +  to SystemResource Table.

2023-01-02 07:20 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/To2Blob.java
> +      logger.info("To2 doGet body : " + body);
TO2  Body:

2023-01-02 07:20 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/api/To2Blob.java
> +    logger.info("To2 doPost body : " + body);
TO2 body

2023-01-02 07:21 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/db/To0Scheduler.java
Revert changes in this file.

2023-01-02 07:22 UTC, DukeDavis12 commented on protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
> -      boolean verifiedRedirect = cs.verify(storedRedirectEntry.getTo1d(), ownerPublicKey);
Revert changes in this file.

2023-01-02 07:23 UTC, DukeDavis12 requested changes
Please address the comments.

2023-01-16 07:42 UTC, DukeDavis12 submitted a review, later dismissed

2023-03-01 08:20 UTC, KiranSukhavasi approved these changes

2023-03-20 07:52 UTC, closed without merging