Added storage call to get HMAC replacement key and update credentials
secure-device-onboard/pri-fidoiot pull request #7
Opened 2020-10-09 02:36 UTC by rftemple

Storage client updates credentials and checks for credential re-use protocol.
Client has choice to support re-use by returning null for the replacement HMAC
or to go ahead and return a new HMAC.

Signed-off-by: Templeton, Randall <randall.f.templeton@intel.com>

2020-10-12 16:36 UTC, johneasterday approved these changes

2020-10-12 16:37 UTC, grbean approved these changes

2020-10-12 16:57 UTC, prateekcr commented on protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
> +        .set(Const.DC_PROTVER,
New creds is being initialized with old creds. So, the GUID and RV info comparison would always match. Should be initialized with values from 'message'.

2020-10-12 17:27 UTC, trbehera requested changes
Pending review comments from Prateek.

2020-10-14 05:25 UTC, trbehera approved these changes

2020-10-14 05:25 UTC, merged